// <auto-generated />
using AA.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AA.Migrations
{
    [DbContext(typeof(MascotaContext))]
    [Migration("20190613044906_usuariosiniciales1.0")]
    partial class usuariosiniciales10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AA.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodigoMascota")
                        .IsRequired();

                    b.Property<int>("Edad");

                    b.Property<string>("Foto")
                        .IsRequired();

                    b.Property<string>("NombreMascota")
                        .IsRequired();

                    b.Property<int>("Peso");

                    b.Property<int>("TipoId");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Mascotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoMascota = "ACM2PL",
                            Edad = 18,
                            Foto = "https://estaticos.muyinteresante.es/media/cache/760x570_thumb/uploads/images/article/5c3871215bafe83b078adbe3/perro.jpg",
                            NombreMascota = "Julito",
                            Peso = 1900,
                            TipoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CodigoMascota = "RGM2PL",
                            Edad = 5,
                            Foto = "https://mxcity.mx/wp-content/uploads/2017/08/1-9.jpg",
                            NombreMascota = "Ronina",
                            Peso = 800,
                            TipoId = 1
                        },
                        new
                        {
                            Id = 3,
                            CodigoMascota = "GAT001",
                            Edad = 2,
                            Foto = "https://www.notigatos.es/wp-content/uploads/2017/10/gatito-830x552.jpg",
                            NombreMascota = "Michi",
                            Peso = 250,
                            TipoId = 2
                        },
                        new
                        {
                            Id = 4,
                            CodigoMascota = "TAPIR590",
                            Edad = 19,
                            Foto = "https://www.elpopular.pe/sites/default/files/styles/img_620x465/public/imagen/2019/03/22/Noticia-232947-youtube_tapir_590_sufre_estafa_con_sus_redes_sociales_y_hace_pedido_a_seguidores.png?itok=NeTL_yoG",
                            NombreMascota = "Oliver",
                            Peso = 590,
                            TipoId = 3
                        });
                });

            modelBuilder.Entity("AA.Models.Solicitud", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApellidoMaterno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired();

                    b.Property<string>("CodigoM")
                        .IsRequired();

                    b.Property<string>("Correo")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Telefono")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("AA.Models.TipoMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Perro"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Gato"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Tapir"
                        });
                });

            modelBuilder.Entity("AA.ViewModels.LoginModel", b =>
                {
                    b.Property<string>("Usuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Usuario");

                    b.ToTable("LoginModel");

                    b.HasData(
                        new
                        {
                            Usuario = "admin",
                            Password = "admin"
                        },
                        new
                        {
                            Usuario = "diego",
                            Password = "diego"
                        },
                        new
                        {
                            Usuario = "giacomo",
                            Password = "giacomo"
                        });
                });

            modelBuilder.Entity("AA.Models.Mascota", b =>
                {
                    b.HasOne("AA.Models.TipoMascota", "Tipo")
                        .WithMany("Mascotas")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
